"""Initial migration

Revision ID: 60e9f47fec54
Revises: 
Create Date: 2026-07-03 23:11:12.760705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e9f47fec54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.Text(), nullable=False),
    sa.Column('short_url', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_url_short_url'), ['short_url'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_short_url'))
        batch_op.drop_index(batch_op.f('ix_url_expires_at'))

    op.drop_table('url')
    # ### end Alembic commands ###
