"""Initial migration

Revision ID: 7bddaced8516
Revises: 
Create Date: 2026-07-03 01:34:51.014128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bddaced8516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.alter_column('short_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_expires_at'))
        batch_op.drop_index(batch_op.f('idx_short_url'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_short_url'), ['short_url'], unique=False)
        batch_op.create_index(batch_op.f('idx_expires_at'), ['expires_at'], unique=False)
        batch_op.alter_column('short_url',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
