"""Initial migration

Revision ID: a8d9c08902f8
Revises: 
Create Date: 2026-07-03 22:46:17.605707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8d9c08902f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.alter_column('short_url',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('unique_short_url'), type_='unique')
        batch_op.drop_constraint(batch_op.f('url_short_url_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_url_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_url_short_url'), ['short_url'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_short_url'))
        batch_op.drop_index(batch_op.f('ix_url_expires_at'))
        batch_op.create_unique_constraint(batch_op.f('url_short_url_key'), ['short_url'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('unique_short_url'), ['short_url'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('short_url',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
